def data_analyze(data):
    print("#" * 30, "First 5 rows of data", "#" * 30)
    print(data.head())
    print("#" * 30, "Data information", "#" * 30)
    print(data.info())
    print("#" * 30, "Data describe", "#" * 30)
    print(data.describe().T)
    print("#" * 30, "Data null count", "#" * 30)
    print(data.isnull().sum())
    print("#" * 30, "Data shape", "#" * 30)
    print(data.shape)
    print("#" * 30, "Data columns", "#" * 30)
    print(data.columns)
    print("#" * 30, "Data types", "#" * 30)
    print(data.dtypes)
    print("#" * 30, "Data unique values", "#" * 30)
    print(data.nunique())
    print("*" * 100)